---
- name: APT update & upgrade only if updates exist
  hosts: all
  become: yes

  vars:
    ansible_command_timeout: 120

  tasks:

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Check how many packages would be upgraded
      ansible.builtin.command: apt-get --just-print upgrade
      register: upgrade_check
      changed_when: false

    - name: Extract number of upgradeable packages
      ansible.builtin.set_fact:
        upgrade_count: "{{ upgrade_check.stdout | regex_findall('Inst ') | length }}"

    - name: Anzahl upgradebarer Pakete anzeigen
      ansible.builtin.debug:
        msg: "Es sind {{ upgrade_count }} Pakete upgradebar."

    - name: Upgrade durchführen, wenn Pakete vorhanden sind
      ansible.builtin.apt:
        upgrade: yes
      when: upgrade_count | int > 0

    - name: Abschlussmeldung
      ansible.builtin.debug:
        msg: "APT-Upgrade-Check abgeschlossen: Alle Hosts sind aktuell oder wurden aktualisiert."
      run_once: true
      delegate_to: localhost
      changed_when: false
